name: Generate Ideas from Reddit Posts

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-ideas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run Idea Generation Job
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
        run: |
          echo "🚀 Starting idea generation job..."
          response=$(curl -s -X POST "$NEXT_PUBLIC_SITE_URL/api/jobs/generate-ideas")
          echo "Response: $response"

          # Check if the response contains success
          if echo "$response" | grep -q '"success":true'; then
            echo "✅ Idea generation job completed successfully"
          else
            echo "❌ Idea generation job failed"
            echo "$response"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Idea generation job failed at $(date)"
          echo "Check the logs above for details"
