# name: Generate Ideas from Reddit Posts

# jobs:
#   generate-ideas:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Check required secrets
#         run: |
#           echo "🔍 Checking required secrets..."
#           if [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ]; then
#             echo "❌ NEXT_PUBLIC_SUPABASE_URL is not set"
#             exit 1
#           fi
#           if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
#             echo "❌ SUPABASE_SERVICE_ROLE_KEY is not set"
#             exit 1
#           fi
#           if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
#             echo "❌ OPENAI_API_KEY is not set"
#             exit 1
#           fi
#           if [ -z "${{ secrets.NEXT_PUBLIC_SITE_URL }}" ]; then
#             echo "❌ NEXT_PUBLIC_SITE_URL is not set"
#             exit 1
#           fi
#           echo "✅ All required secrets are present"

#       - name: Run Idea Generation Job
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
#           SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#           NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
#         run: |
#           echo "🚀 Starting idea generation job..."
#           echo "Target URL: $NEXT_PUBLIC_SITE_URL/api/jobs/generate-ideas"

#           # Test if the endpoint is accessible
#           if ! curl -s --head "$NEXT_PUBLIC_SITE_URL/api/jobs/generate-ideas" | grep -q "200\|405"; then
#             echo "❌ API endpoint is not accessible. Please ensure your application is deployed and running."
#             exit 1
#           fi

#           response=$(curl -s -X POST "$NEXT_PUBLIC_SITE_URL/api/jobs/generate-ideas")
#           echo "Response: $response"

#           # Check if the response contains success
#           if echo "$response" | grep -q '"success":true'; then
#             echo "✅ Idea generation job completed successfully"
#           else
#             echo "❌ Idea generation job failed"
#             echo "$response"
#             exit 1
#           fi

#       - name: Notify on failure
#         if: failure()
#         run: |
#           echo "❌ Idea generation job failed at $(date)"
#           echo "Check the logs above for details"
